### ISSUE TITLE
Failed after update event

### ISSUE THREAD

**Issue by splasky** [TGmeetup/TGmeetup#35]
Failed after command python tgmeetup.py -u
here are stack trace:
```python tgmeetup.py -u
Update all the meetup infomation.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/splasky/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/splasky/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/splasky/Desktop/TGmeetup/TGmeetup/eventparsing.py", line 60, in add_meetup_event
    access_token = meetup_api.refresh_access_token()
  File "/home/splasky/Desktop/TGmeetup/TGmeetup/libs/RegistrationAPI/Meetup.py", line 20, in refresh_access_token
    return result.json()["access_token"]
KeyError: 'access_token'
```
Test platform:
ubuntu 18.04,python 3.7

**Comment by sufuf3** [comment]
Hi, @splasky Thanks for the issue.
May I ask you have done you sign up Meetup API OAuth consumer & modify API.cfg?
Here are reference
- https://secure.meetup.com/meetup_api/oauth_consumers/create/ 
- https://hackmd.io/s/ByrxYmi4G

Thank you.

**Comment by splasky** [comment]
solve
