### ISSUE TITLE
ImportError: No module named geopy.geocoders

### ISSUE THREAD

**Issue by tonyyang924** [TGmeetup/TGmeetup#77]
I have installed TGmeetup by "install.sh" shell script.
But when I run 'tgmeetup' command, showed up this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/tgmeetup", line 11, in <module>
    load_entry_point('tgmeetup==0.2.1', 'console_scripts', 'tgmeetup')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.13-x86_64/egg/TGmeetup/tgmeetup.py", line 14, in <module>
  File "build/bdist.macosx-10.13-x86_64/egg/TGmeetup/eventparsing.py", line 13, in <module>
  File "build/bdist.macosx-10.13-x86_64/egg/TGmeetup/libs/RegistrationAPI/KKTIX.py", line 6, in <module>
ImportError: No module named geopy.geocoders
```

My system has python2 and python3 simultaneously. 
It seems to not be affect. 
I also run pip install geopy but still showed same error message.

**Comment by sufuf3** [comment]
Hi @tonyyang924 Thank you for your report.

Because python2 will retire in 2020, let's use python3. What do you think?
Would you please try `pip3 install geopy`?
I've created a #78. Maybe you can refer to it and help you with troubleshooting.
If there is any question, please let me help you.

Thank you.

**Comment by tonyyang924** [comment]
@sufuf3 
Thanks for your reply.
Yes, I've tried `pip3 install geopy` that I'm sure the library had been installed in python3.
I've also bound alias `alias python="python3" alias pip="pip3"` before I run `make install`.
So I just confused why I run `tgmeetup` which chooses python2 instead of python3.

I tried #78 pull requested changes that works for me! Thank you.
```
➜  TGmeetup git:(78) make instal
Requirement already satisfied: configparser in /usr/local/lib/python3.7/site-packages (3.7.4)
Password:
running install
...
```

```
➜  TGmeetup git:(78) tgmeetup      
╔══════════════════════════════════════════════════╦═══════════╦══════════════════════╗
║ Title(name)                                      ║ City      ║ Link / Meetup / Date ║
╠══════════════════════════════════════════════════╬═══════════╬══════════════════════╣
║ 台中自由軟體愛好者社群 (TFC)                     ║ Taichung  ║                      ║
║ (TFC)                                            ║           ║                      ║
║ DevOps Taiwan                                    ║ Taipei    ║                      ║
║ (DevOpsTaiwan)                                   ║           ║                      ║
║ Kaohsiung Linux User Group                       ║ Kaohsiung ║                      ║
║ (KaLUG)                                          ║           ║                      ║
```

**Comment by sufuf3** [comment]
Awesome! 👍 
Thank you. :)
